name: Build Image

on:
  push:
    tags:
      - '*'

jobs:
  Run-Build-Script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/login-action@v3
        with:
          username: hetsh
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: ./build.sh --upload
